#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
zxkbmap de &
picom -f &
sh $HOME/.config/polybar/launch.sh &
sh $HOME/.conf/bspwm/pywal.sh &
nitrogen --restore &
xinput --set-prop 12 'libinput Accel Speed' 0.7 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

